version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  next:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://johndoe:randompassword@postgres:5432/postgres
    depends_on:
      - postgres

volumes:
  postgres: